const skills = [
  "Agile Methodology",
  "Asana",
  "AWS",
  "AWS EC2",
  "Babel",
  "Bootstrap",
  "Circle CI",
  "CodeIgniter",
  "Collaboration",
  "Communication",
  "Confluence",
  "CSS3",
  "Django",
  "Docker",
  "EntQL",
  "ES6/ES7",
  "Express.js",
  "Flask",
  "Git",
  "GitHub",
  "Gitlab",
  "GraphQL",
  "Guru",
  "Hack",
  "HTML5",
  "JavaScript",
  "Jest",
  "Jira",
  "Material UI",
  "Mercurial",
  "MongoDB",
  "MVC Architecture",
  "MySQL",
  "Node.JS",
  "Passionate",
  "PHP",
  "Pixel-Perfect Styled Components",
  "Positive Attitude",
  "PostgreSQL",
  "Python",
  "React Testing Library",
  "React.js",
  "Redis",
  "Redux",
  "Relay",
  "RSpec",
  "Ruby",
  "Ruby on Rails",
  "Ruby Version Manager",
  "Sass/Less/Scss",
  "Sidekiq",
  "Slack",
  "Software Development Life Cycle",
  "Storybook",
  "Tailwind",
  "Team Player",
  "Technical Documentation",
  "Test Driven Development",
  "Time Management",
  "TypeScript",
  "Vite",
  "Vue.js",
  "Vuex",
  "Webpack",
];

export default skills;
