const skills = [
  "Agile/Scrum Methodology",
  "AI-SDLC",
  "Asana",
  "AWS",
  "AWS EC2",
  "Babel",
  "Bootstrap",
  "Chakra UI",
  "Circle CI",
  "CodeIgniter",
  "Confluence",
  "CSS3",
  "CursorAI",
  "DeepSeek",
  "Django",
  "Docker",
  "Express.js",
  "Firebase",
  "Firestore",
  "Flask",
  "GCP (Google Cloud)",
  "Gemini",
  "Git",
  "GitHub",
  "GitLab",
  "Google Cloud Services",
  "GraphQL",
  "Hacklang",
  "HTML5",
  "Iterative Delivery",
  "JavaScript",
  "Jest",
  "JIRA",
  "LangChain",
  "Load Balancers",
  "Material UI",
  "Mercurial",
  "Microsoft Teams",
  "MongoDB",
  "MVC Architecture",
  "MySQL",
  "Nest.js",
  "Next.js",
  "Node.js",
  "OpenAI",
  "PHP",
  "Pixel-Perfect Components",
  "PostgreSQL",
  "Python",
  "React Testing Library",
  "React.js",
  "Redis",
  "Redux",
  "Relay",
  "RSpec",
  "Ruby",
  "Ruby on Rails",
  "Ruby Version Manager",
  "Sass/Less/Scss",
  "ShapeUp Method (preferred)",
  "Sidekiq",
  "Slack",
  "Software Development Life Cycle (SDLC)",
  "Storybook",
  "Structured Output",
  "Styled-components",
  "Tailwind CSS",
  "Technical Documentation",
  "Terraform",
  "Test Driven Development",
  "TypeScript",
  "VertexAI",
  "Vite",
  "Vue.js",
  "Vuex",
  "Webpack",
];

export default skills;
