const skills = [
  "Agile/Scrum Methodology",
  "Asana",
  "AWS",
  "AWS EC2",
  "Babel",
  "Bootstrap",
  "Chakra UI",
  "Circle CI",
  "CodeIgniter",
  "Confluence",
  "CSS3",
  "DeepSeek",
  "Django",
  "Docker",
  "Express.js",
  "Flask",
  "Gemini",
  "Git",
  "GitHub",
  "GraphQL",
  "Hacklang",
  "HTML5",
  "JavaScript",
  "Jest",
  "JIRA",
  "LangChain",
  "Material UI",
  "Mercurial",
  "MongoDB",
  "MVC Architecture",
  "MySQL",
  "Nest.js",
  "Next.js",
  "Node.js",
  "OpenAI",
  "PHP",
  "Pixel-Perfect Components",
  "PostgreSQL",
  "Python",
  "React Testing Library",
  "React.js",
  "Redux",
  "Relay",
  "RSpec",
  "Ruby",
  "Ruby on Rails",
  "Ruby Version Manager",
  "Sass/Less/Scss",
  "Sidekiq",
  "Slack",
  "Software Development Life Cycle (SDLC)",
  "Storybook",
  "Structured Output",
  "Tailwind CSS",
  "Technical Documentation",
  "Test Driven Development",
  "TypeScript",
  "Vertex",
  "Vite",
  "Vue.js",
];

export default skills;
