const experiences = [
  {
    jobTitle: "📚 Senior Software Engineer",
    startYear: 2024,
    endYear: "Present",
    companyName: "Undisclosed Major Education Provider",
    city: "Seattle",
    stateAbbreviation: "WA",
  },
  {
    jobTitle: "🚴‍♂️Senior Software Engineer",
    startYear: 2023,
    endYear: 2024,
    companyName: "Ridepanda",
    city: "Seattle",
    stateAbbreviation: "WA",
  },
  {
    jobTitle: "🏥 Software Engineer",
    startYear: 2022,
    endYear: 2023,
    companyName: "Sana Benefits",
    city: "Seattle",
    stateAbbreviation: "WA",
  },
  {
    jobTitle: "🧑‍💻 Software Engineer",
    startYear: 2019,
    endYear: 2022,
    companyName: "Perficient, Inc.",
    city: "Seattle",
    stateAbbreviation: "WA",
  },
  {
    jobTitle: "🌲 Software Engineer",
    startYear: 2016,
    endYear: 2019,
    companyName: "Sasquat.ch",
    city: "Bothell",
    stateAbbreviation: "WA",
  },
  {
    jobTitle: "👨‍⚕️ Web Developer",
    startYear: 2015,
    endYear: 2016,
    companyName: "Sesame Communication",
    city: "Seattle",
    stateAbbreviation: "WA",
  },
  {
    jobTitle: "⚛️ Web Developer",
    startYear: 2011,
    endYear: 2015,
    companyName: "SmartGuys Design",
    city: "Seattle",
    stateAbbreviation: "WA",
  },
  // {
  //   jobTitle: "🛠️ Web Developer",
  //   startYear: 2011,
  //   endYear: 2012,
  //   companyName: "National Outdoor Leadership School",
  //   city: "Lander",
  //   stateAbbreviation: "WY",
  // },
];

export default experiences;
